const Products = [
	{
		id: 20,
		date: 1659205052145,
		title: 'Sony WH-1000XM4 Wireless Noise-Canceling Headphones - Black',
		images: [
			'https://m.media-amazon.com/images/I/71Xcl-j5ipL._AC_SX679_.jpg',
			'https://m.media-amazon.com/images/I/71aYO9W6LuL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71PQVJkcNuL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81+QNllRMUL._AC_SL1500_.jpg',
		],
		category: 'computer-accessories',
		condition: 'used',
		details: [
			'Designed for everywhere you game, with superior sound, comfort and style on all console gaming platforms, including PS5, PS4, Xbox Series X|S, Xbox One, Nintendo Switch, and mobile',
			'Widely recognized as the best mic in gaming, the Discord-certified ClearCast microphone delivers studio-quality voice clarity and background noise cancellation',
			'Sound is your competitive advantage with the S1 speaker drivers, engineered to produce ultra-low distortion audio so you hear every detail',
			'Play all day with athletics-inspired performance fabric AirWeave ear cushions that keep your ears cool and dry',
			'The exclusive ski goggle suspension headband perfectly contours across your entire head, comfortably distributing the weight and eliminating pressure points',
		],
		price: 120.5,
	},
	{
		id: 17,
		date: 1659205052245,
		title: 'Razer DeathAdder Essential Gaming Mouse: 6400 DPI Optical Sensor - 5 Programmable Buttons - Mechanical Switches - Rubber Side Grips - Classic Black',
		price: 70,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/8189uwDnMkL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/612ydhRz3XS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/61Vbk62PIjS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71VkGcn9VZL._AC_SL1500_.jpg',
		],
		category: 'computer-accessories',
		details: [
			'The Best-Selling Gaming Peripherals Manufacturer in the US: Source - The NPD Group, Inc. U.S. Retail Tracking Service, Keyboards, Mice, PC Headset/Pc Microphone, Gaming Designed, based on dollar sales, 2017-2021',
			'High-Precision 6,400 DPI Optical Sensor: Offers on-the-fly sensitivity adjustment through dedicated DPI buttons (reprogrammable) for gaming and creative work',
			'Durable Mechanical Switches: Supports up to 10 million clicks, backed by a 2 year warranty',
			'Ridged, Rubberized Scroll Wheel for Maximum Accuracy: Small, tactile bumps increases grip and allows for more controlled scrolling in high-stakes gaming situations',
			'5 Programmable Buttons: Allows for button remapping and assignment of complex macro functions through Razer Synapse',
		],
	},
	{
		id: 3,
		date: 1659206052145,
		title: 'X Rocker Mammoth Pedestal 2.1 BT PC Office Gaming Chair, 32" x 26" x 40.9", Black',
		images: [
			'https://m.media-amazon.com/images/I/61DHEGaky+L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81eIAq1CqxL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81JgIn5s6eL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/715DTFYAi9L._AC_SL1500_.jpg',
		],
		category: 'office-furniture',
		condition: 'new',
		details: [
			'HIGH TECH GAMING CHAIR: Upgrade your gaming setup with headrest mounted speakers and a backrest mounted subwoofer that provide high quality audio and real-time vibration for an immersive experience',
			'COMPATIBLE WITH MOST GAMING SYSTEMS: Conveniently connect to most gaming systems or Bluetooth enabled devices so you can enjoy video games, movies, music, and more',
			'PEDESTAL SWIVEL BASE: Ergonomic design and sturdy pedestal swivel base provide maximum support and mobility during your longest gaming sessions',
			'MODERN DESIGN: Black faux leather design brings a modern look to your office, living room, game room, bedroom, or dorm room',
			'CONVENIENT FOLDABLE SIZE: Measures 32" x 26" x 40.9" and folds down for convenient storage when not in use',
		],
		price: 90.3,
	},
	{
		id: 15,
		date: 16592060521453,
		title: 'Sceptre 24" Professional Thin 75Hz 1080p LED Monitor 2x HDMI VGA Build-in Speakers, Machine Black (E248W-19203R Series)',
		price: 99,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/71rXSVqET9L._AC_SL1257_.jpg',
			'https://m.media-amazon.com/images/I/61ErMXHUtRL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/61QlrzZuj6L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/61FU4QixmRL._AC_SL1500_.jpg',
		],
		category: 'monitors',
		details: [
			'24" Ultra slim profile',
			'Contemporary sleek metallic design',
			'Slim bezel with thin chassis. Power Range (V, A, Hz)- AC-DC Adapter Input 100 – 240 VAC, 50/60 Hz, 1.0A (Max.) Output - 12V DC, 2.5A. Power Consumption (Typical)- 25.4W. Neck/Stand Detachable: Yes',
			'2 x HDMI Ports (convertible to DVI).Contrast Ratio:1000 : 1',
			'VESA wall mount ready. HDMI Input Signal Support - 1920 x 1080 @ 75Hz, 1080/60p, 1080/60i, 720p, 480p, 480i, Built-in Speakers - 2 x 2W 8 Ohm.Mounting type: VESA Hole Pattern 100mm x 100mm',
		],
	},
	{
		id: 5,
		date: 16592060521452,
		title: 'AMD Ryzen 5 5600X 6-core, 12-Thread Unlocked Desktop Processor with Wraith Stealth Cooler',
		price: 250,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/61vGQNUEsGL._AC_SL1384_.jpg',
			'https://m.media-amazon.com/images/I/71KV0V8AxbL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/61uUIygd0JS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81ciJn85chL._AC_SL1500_.jpg',
		],
		category: 'computer-components',
		details: [
			"AMD's fastest 6 core processor for mainstream desktop, with 12 processing threads",
			"Can deliver elite 100 plus FPS performance in the world's most popular games",
			'Bundled with the quiet, capable AMD Wraith Stealth cooler. System Memory Type: DDR4',
			'4.6 GHz Max Boost, unlocked for overclocking, 35 MB of cache, DDR-3200 support',
			'For the advanced Socket AM4 platform, can support PCIe 4.0 on X570 and B550 motherboards',
		],
	},
	{
		id: 6,
		date: 16592060521352,
		title: 'SAMSUNG Galaxy A53 5G A Series Cell Phone, Factory Unlocked Android Smartphone, 128GB, 6.5” FHD Super AMOLED Screen, Long Battery Life, US Version, Black',
		price: 324.99,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/71HN4P-pd5L._AC_SL1223_.jpg',
			'https://m.media-amazon.com/images/I/61JdAMNhFUL._AC_SL1199_.jpg',
			'https://m.media-amazon.com/images/I/4162nvl6UCL._AC_SL1199_.jpg',
			'https://m.media-amazon.com/images/I/31rG76KG2VL._AC_SL1199_.jpg',
		],
		category: 'smartphones',
		details: [
			'LONG-LASTING BATTERY: Your busy life deserves a battery built for busy; Whether you’re taking a video call on your commute, catching up on your favorite show or with friends and family, your long-lasting, super fast charging battery* has your back',
			'POWERFUL PERFORMANCE: The very best of Galaxy A Series gives you awesomely smooth streaming of your favorite content with the most powerful performance in its series and awesomely fast speeds to download shows and movies — all at the speed of 5G**',
			'INTELLIGENT CAMERA: Capturing content is as easy as pose, shoot and share with A53 5G’s*** intelligent camera; Single Take***** lets you capture video, pictures and more with just one tap, while image stabilization technology makes sure every clip is crystal clear',
			'MODERN DESIGN: Life happens, but Galaxy A53 5G*** provides a premium slim design that is built to last through those unpredictable moments; The body was engineered to endure, so you can worry less around water and dust*******',
			'PRIVACY & SECURITY: Protect your data with multilayered Knox Security; Also, with Private Share********, you can set time limits and expiration dates on all shared files, revoke access at any time and ensure the intended recipient is the only one who can open your files — and that they cannot send or screenshot your stuff',
		],
	},
	{
		id: 18,
		date: 16592060521455,
		title: 'SAMSUNG 970 EVO Plus SSD 2TB - M.2 NVMe Interface Internal Solid State Drive with V-NAND Technology (MZ-V7S2T0B/AM)',
		price: 165.69,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/813bvfaxuAL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81HKVugDtRL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/41cUfgtV+HL._AC_.jpg',
			'https://m.media-amazon.com/images/I/41q3UHp1TeL._AC_.jpg',
		],
		category: 'computer-components',
		details: [
			'INNOVATIVE V-NAND TECHNOLOGY: Powered by Samsung V-NAND Technology, the 970 EVO Plus SSD’s NVMe interface (PCIe Gen 3.0 x4 NVMe 1.3) offers enhanced bandwidth, low latency, and power efficiency ideal for tech enthusiasts, high end gamers, and 4K & 3D content designers',
			'BREAKTHROUGH READ WRITE SPEEDS: Sequential read and write performance levels of up to 3,500MB s and 3,300MB s, respectively; Random Read (4KB, QD32): Up to 600,000 IOPS Random Read',
			'PERFORMANCE OPTIMIZATION AND DATA SECURITY: Seamless cloning and file transfers with Samsung Magician Software, the ideal SSD management solution for performance optimization and data security with automatic firmware updates',
			'5-YEAR LIMITED WARRANTY: 5-year limited warranty or 600 TBW (Terabytes Written)',
			'Note: Model: MZ-V7S2T0 on packaging is the model number and Item model number provided MZ-V7S2T0B AM is technically the item code which shows country of intended sale',
		],
	},
	{
		id: 8,
		date: 16592060521459,
		title: 'HP DeskJet 2755e Wireless Color All-in-One Printer with bonus 6 months Instant Ink with HP+ (26K67A), white',
		price: 150,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/61UdeL7aO-L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71SuAsK-iBL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71WPT7wBAIL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71L3NvTpZqL._AC_SL1500_.jpg',
		],
		category: 'printers',
		details: [
			"6 FREE MONTHS INSTANT INK SUBSCRIPTION when you activate HP+ – Print up to 700 pages a month. Ink ships to you automatically so you never run out. After 6 months, monthly fee applies unless cancelled, and you'll save up to 50% on ink.",
			'INCLUDES FREE HP+ SMART FEATURES – Activate HP+ free to get advanced features for mobile printing, security, automatic updates and more. HP+ only works with an HP account, internet connection and Original HP Ink for the life of the printer.',
			'BEST FOR BASIC PRINTING – Print basic color documents like recipes, forms and travel documents',
			'KEY FEATURES – Print, copy and scan in color, plus mobile and wireless printing',
			'HP SMART APP – Print, scan and copy from your phone—whenever, wherever. Get advanced features for 24 months with HP+.',
		],
	},
	{
		id: 9,
		date: 1659203052145,
		title: 'Razer Enki Gaming Chair: All-Day Gaming Comfort - Built-in Lumbar Arch - Optimized Cushion Density - Dual-Textured, Eco-Friendly Synthetic Leather - Reactive Seat Tilt & 152-Degree Recline - Pink',
		price: 249.99,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/61yzRd+LN+L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71m5ZTlwpyL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71EmyIJNQhL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71jCIaBCQ1L._AC_SL1500_.jpg',
		],
		category: 'office-furniture',
		details: [
			'Designed for All-Day Gaming: 110-degree shoulder arches and wide 54-cm seat base ensure optimal weight distribution for long-lasting comfort during gaming marathons',
			'Built-in Lumbar Arch: Feel less fatigued over long periods with the lumbar curve that gently supports your lower back and encourages sitting in a neutral position',
			'Optimized Cushion Density: Unparalleled comfort with a softer seat base for a cushier feel and a firmer seat backing for solid support',
			'4D Armrests: Adjust the armrests’ height, angle and move them forwards or backwards for a position tailored to the way you sit',
			'Premium Memory Foam Head Cushion: Included plush head cushion that can mold to the shape of your head and neck, providing cushy support to those key areas',
		],
	},
	{
		id: 16,
		date: 1659276052145,
		title: 'Aic Advanced Industrial Computer RSC-2ET Storage Server Chassis, 12G EOB backplane, Acbel 2U 800W HRP Platinum, 2X 7mm 2.5" hot-swap OS, Rail, Black, (RSC-2ET-80HP-SA3E-0EL-B)',
		price: 420,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/31+YbMUwLzL._AC_.jpg',
			'https://m.media-amazon.com/images/I/41jvvgP6FlL._AC_.jpg',
			'https://m.media-amazon.com/images/I/512ph1LSSFL._AC_.jpg',
			'https://m.media-amazon.com/images/I/319P2ReJN2L._AC_.jpg',
		],
		category: 'servers',
		details: [
			'800W 1+1 redundant PSU PMBus 1.2 80+ Platinum',
			'12G EOB backplane',
			'Tool-less 3.5" & 2.5" drive trays, 2x 7mm 2.5" hot-swap OS',
			'Heavy-duty preplated SPGC cold-rolled steel',
			'3 x 80x38mm PWM & low-power consumption hot swap fans',
		],
	},
	{
		id: 11,
		date: 16592060492145,
		title: 'Brother Wireless Portable Compact Desktop Scanner, ADS-1250W, Easy-to-Use, Fast Scan Speeds, Ideal for Home, Home Office or On-the-Go Professionals',
		price: 380,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/71UsBocQuwL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81KdIq79TpL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81Ky03cfgeL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81NiyT6Y8BL._AC_SL1500_.jpg',
		],
		category: 'scanners',
		details: [
			'COMPACT DESIGN AND FAST SCAN SPEEDS HANDLE A VARIETY OF DOCUMENTS Scan single and double sided, documents in a single pass at up to 25 ppm(1). Dedicated card slot to scan plastic cards, plus 20 page capacity auto document feeder for multi page scanning',
			'VERSATILE CONNECTIVITY AND PORTABILITY Use the Micro USB 3.0 connection to a laptop or PC for easy device portability (8). Wireless scanning to PC, cloud apps (7), and mobile destinations plus USB 3.0 interface for local connections',
			'QUICK AND EASY SCANNING WITHOUT INSTALLING SOFTWARE Start scanning immediately without installing software. Mass storage support via scan to USB allows scanning and retrieval of files simply by opening the drive on your connected PC',
			'COMPATIBLE WITH THE WAY YOU WORK ADS1250W supports multiple “Scan to” destinations: such as File(2), OCR(2), Email(2), Mobile Devices(3) and USB flash memory drive(4) to help optimize your business processes',
			'OPTIMIZE IMAGES AND TEXT Enhance scans with automatic color detection/adjustment, image rotation (PC only), bleed through prevention / background removal, text enhancement, color drop. Software suite(6) includes document management and OCR software.Resolution:600',
		],
	},
	{
		id: 12,
		date: 1659206052145543,
		title: 'Fujitsu ScanSnap iX1600 Deluxe Color Duplex Document Scanner with Adobe Acrobat DC Pro for Mac and PC, Black',
		price: 550,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/71u7Psu+y7L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81rng8vG3VS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71d5IsNdutS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/815uD9hyPtS._AC_SL1500_.jpg',
		],
		category: 'scanners',
		details: [
			'Includes 1-year subscription to Adobe Acrobat Pro DC for Mac or PC - Turn scanned documents into editable searchable PDFs',
			'Optimized user experience: ScanSnap iX1600 features an intuitive 4.3inch touch screen for complete end to end scanning and data utilization',
			'Customize your preference: The scanner supports up to 30 customizable profiles; Customize the profile on the touch screen based on your scanning needs and personalize scanning icons using color, icons or letters',
			'Scan anywhere you want whenever you want: Wi-Fi compatibility allows you to directly connect to your smart devices or cloud services without a PC, and allows for flexible placement wherever its convenient',
			'Ideal for team sharing with stress-free usability: One scanner supports up to 4 user licenses each, allowing user profile and icon customizations; Friendly interface allows even the most technology challenged users to scan and complete tasks with peace of mind',
		],
	},
	{
		id: 13,
		date: 16592077052145,
		title: 'Seagate Portable 2TB External Hard Drive Portable HDD – USB 3.0 for PC, Mac, PlayStation, & Xbox - 1-Year Rescue Service (STGX2000400)',
		price: 99.99,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/81tjLksKixL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/91QqR55XhQL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/918-cGeMaRL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71+JNapCNaL._AC_SL1500_.jpg',
		],
		category: 'data-storage',
		details: [
			'Easily store and access 2TB to content on the go with the Seagate Portable Drive, a USB external hard drive',
			'Designed to work with Windows or Mac computers, this external hard drive makes backup a snap just drag and drop',
			'Designed to work with Windows or Mac computers, this external hard drive makes backup a snap just drag and drop',
			'To get set up, connect the portable hard drive to a computer for automatic recognition no software required',
			'This USB drive provides plug and play simplicity with the included 18 inch USB 3.0 cable',
		],
	},
	{
		id: 14,
		date: 1659206352145,
		title: 'Logitech MK270 Wireless Keyboard And Mouse Combo For Windows, 2.4 GHz Wireless, Compact Mouse, 8 Multimedia And Shortcut Keys, For PC, Laptop - Black',
		price: 70,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/61pUul1oDlL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71X4aSJLm5L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/61ZsKv3VLAL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71uyjnDANeL._AC_SL1500_.jpg',
		],
		category: 'computer-accessories',
		details: [
			'Reliable Plug and Play: The USB receiver provides a reliable wireless connection up to 33 ft (1), so you can forget about drop-outs and delays and you can take it wherever you use your computer',
			'Type in Comfort: The design of this keyboard creates a comfortable typing experience thanks to the low-profile, quiet keys and standard layout with full-size F-keys, number pad, and arrow keys',
			'Durable and Resilient: This full-size wireless keyboard features a spill-resistant design (2), durable keys and sturdy tilt legs with adjustable height',
			"Favorite Wireless Combo: MK270 brings together familiar typing, wireless freedom, and long battery life; no wonder this is the world's top-selling combo(4)",
			'Upgrade to Logitech MK540 Combo: Experience increased comfort with the MK540 combo, featuring scooped keys, palm rest, full-size mouse with soft rubber grips, and customizable shortcuts',
		],
	},
	{
		id: 4,
		date: 1659206053145,
		title: 'Motorola Edge | 2021 | 2-Day battery | Unlocked | Made for US by Motorola | 8/256GB | 108MP Camera | Nebula Blue',
		price: 389.93,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/712nxo9u15L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/51XWLLIOUIS._AC_SL1000_.jpg',
			'https://m.media-amazon.com/images/I/51Ne7bdmwKS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/61DpnBWtd4S._AC_SL1500_.jpg',
		],
		category: 'smartphones',
		details: [
			'Unlocked for the freedom to choose your carrier. 5G service available with 5G plan. 5G network coverage required; available only in select areas. Compatible with T-Mobile 5G and Verizon 5G. Ready for 5G on other select networks dependent on availability; contact your service provider for details. Compatible with all major 4G U.S. carriers, including Verizon, AT&T, and T-Mobile. It also works with prepaid carriers, including Cricket Wireless, Metro by T-Mobile, Simple Mobile, Total Wireless, Tracfone, Net10, Mint, TracFone, Boost, and H2O.',
			'108 MP ultra high-res camera system. Capture high-quality photos and videos with Ultra Pixel technology and 4K video recording.',
			'Ultra-smooth 144Hz display. Bring everything to life in vivid color on a 6.8" HDR10 display with the fastest smartphone refresh rate.',
			'Superfast 5G and Wi-Fi 6E. Download your favorite shows in seconds and join the next-generation of faster Wi-Fi networks.',
			'32 MP high-res selfies. Always look your best and brightest—even at night—with 4x the low-light sensitivity.',
		],
	},
	{
		id: 1,
		date: 165920605214779,
		title: 'Sceptre 30-inch Curved Gaming Monitor 21:9 2560x1080 Ultra Wide Ultra Slim HDMI DisplayPort up to 200Hz Build-in Speakers, Metal Black (C305B-200UN1)',
		price: 999.99,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/612RvBYr4fL._AC_SL1417_.jpg',
			'https://m.media-amazon.com/images/I/614CYMlkYML._AC_SL1329_.jpg',
			'https://m.media-amazon.com/images/I/61v+oRc6GhL._AC_SL1403_.jpg',
			'https://m.media-amazon.com/images/I/71S2h60xgYL._AC_SL1500_.jpg',
		],
		category: 'monitors',
		details: [
			'30" Curved Gaming Monitor 2560 x 1080 Full HD Resolution. Response Time- 5ms GTG',
			'DP Up to 200Hz Refresh Rate / HDMI 2. 0 Up to 120Hz Refresh Rate: More than double the standard refresh rate, 200Hz gives gamers an edge in visibility as frames transition instantly, leaving behind no blurred images',
			"AMD Free Sync With Free Sync, gamers now enjoy smooth video and seamless on the spot movement through their fast paced games. Free Sync is an AMD technology that nearly eliminates tearing and stuttering due to differences between a graphics card's frame rate and a monitor's refresh rate.",
			'Blue Light Shift Reduce your monitors blue light to protect you from eye fatigue, irritation and strains. This enables you to work on you documents, watch movies, or play games more comfortably for extended periods. Gaming LED Light',
			'VESA Wall Mount Pattern Using the VESA wall mount pattern, easily mount your Scepter LED monitor on the wall in a manner that is both aesthetically pleasing and conveniently practical. You will be able to save ample space and view the screen in a position that affords the greatest visibility possible.',
		],
	},
	{
		id: 2,
		date: 16592060372145,
		title: 'EVGA GeForce RTX 3090 FTW3 Ultra Gaming, 24GB GDDR6X, iCX3 Technology, ARGB LED, Metal Backplate, 24G-P5-3987-KR',
		price: 300,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/81QuOSSvYAS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71UjdZuyweS._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71P0zc+dAQL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/71GnuQ-zyCL._AC_SL1500_.jpg',
		],
		category: 'computer-components',
		details: [
			'Real boost clock: 1800 MHz; Memory detail: 24576 MB GDDR6X.',
			'Real-time ray tracing in games for cutting-edge, hyper-realistic graphics.',
			'Triple HDB fans 9 iCX3 thermal sensors offer higher performance cooling and much quieter acoustic noise.',
			'All-metal backplate & adjustable ARGB',
		],
	},
	{
		id: 7,
		date: 16592060521933,
		title: 'SAMSUNG 34-Inch SJ55W Ultrawide Gaming Monitor (LS34J550WQNXZA) – 75Hz Refresh, WQHD Computer Monitor, 3440 x 1440p Resolution, 4ms Response, FreeSync, Split Screen, HDMI, Black',
		price: 780,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/91g-Y1B09EL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81J3Q-RR5EL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/51QOJdu+3vL._AC_SL1204_.jpg',
			'https://m.media-amazon.com/images/I/61oOVqy2E-L._AC_SL1440_.jpg',
		],
		category: 'monitors',
		details: [
			'34-INCH ULTRAWIDE MONITOR with WQHD resolution (3440 x 1440p)',
			'Viewing Angle is 178° (H) / 178° (V); Aspect Ratio is 21:9',
			'AMD FREESYNC synchronizes the refresh rate of your graphics card and widescreen monitor to reduce image tear and stutter',
			'SLIM PANEL, ELEGANT Y-STAND AND METALLIC BEZEL bring quality and style to the workplace or home. Tilt- (-1.5°)（plus/minus 1.0°）upto 15.0°（plus/minus 2.0°）',
			'CONNECT MULTIPLE INPUT SOURCES thru HDMI ports and display port. Power Supply Type - AC 100-240V. Power Consumption (Max)- 59 W. Power Consumption (Stand-by)- less then equal to 0.3 W. Max Stand By Power (DPMS)- less then equal to 0.5 W',
		],
	},
	{
		id: 19,
		date: 165927333052145,
		title: 'Google Pixel 6 – 5G Android Phone - Unlocked Smartphone with Wide and Ultrawide Lens - 128GB - Stormy Black & Pixel 6 Case - Phone Case with Dual-Layer Shock-Absorbing Protection - Stormy Sky',
		price: 1200,
		condition: 'used',
		images: [
			'https://m.media-amazon.com/images/I/61oQtjPpM-L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/51RvcOQxf7L._AC_SL1001_.jpg',
			'https://m.media-amazon.com/images/I/41Dc3f0C50L._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/51+JXaGxvBL._AC_SL1500_.jpg',
		],
		category: 'smartphones',
		details: [
			'Unlocked Android 5G phone gives you the flexibility to change carriers and choose your own data plan[1]; Pixel 6 is fast, smart, and secure, and adapts to you',
			'The powerful Google Tensor processor is the first processor designed by Google and made for Pixel; it keeps your phone fast, your games rich, and your personal info safe',
			'Pixel’s 50 megapixel rear camera captures 150% more light for photos with richer colors and more detail[2]',
			'Professional tools like Magic Eraser[3], Motion Mode, and Portrait Mode keep your photos sharp, accurate, and focused',
		],
	},
	{
		id: 10,
		date: 1659206734145,
		title: 'MSI B550-A PRO ProSeries Motherboard (AMD AM4, DDR4, PCIe 4.0, SATA 6Gb/s, M.2, USB 3.2 Gen 2, HDMI/DP, ATX)',
		price: 320.5,
		condition: 'new',
		images: [
			'https://m.media-amazon.com/images/I/91nx+MhjjwL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/91TZ9hMYEPL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/917DzuUbxxL._AC_SL1500_.jpg',
			'https://m.media-amazon.com/images/I/81QbZcKRiDL._AC_SL1500_.jpg',
		],
		category: 'computer-components',
		details: [
			'Support for 3rd Gen AMD Ryzen processors and future AMD Ryzen processors with BIOS update',
			'Supports dual channel DDR4 memory up to 128 GB (4400 MHz)',
			'Lightning Fast Game experience: PCIe 4.0, Lightning Gen 4 M.2 with M.2 Shield Frozr, AMD Turbo USB 3.2 GEN 2',
			'Core Boost technology combines optimized power circuit layouts and digital power regulation which allows for precise and steady current delivery to the CPU',
			'AUDIO BOOST rewards your ears with studio grade sound quality for immersive gaming experiences',
			'Premium Thermal Solution: Heatsink thermal pad rated for 7W/mk and PCB with 2oz thickened copper',
			'Flash BIOS Button lets users flash the BIOS even without a CPU or memory',
			'Powerful Design: Core Boost, Digital PWM IC, 2oz Thickened Copper PCB, Creator Genie, DDR4 Boost',
		],
	},
];

export default Products;
